apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: devopse2e-deploymnt
spec:
  selector:
    matchLabels:
      app: devopse2e
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: devopse2e
    spec:
      containers:
        - name: devopse2e-k8s
          image: siva2428/devopse2e:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8005 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: devopse2e-svc
spec:
  selector:
    app: devopse2e
  ports:
    - protocol: "TCP"
      port: 8005 # The port that the service is running on in the cluster
      targetPort: 8005 # The port exposed by the service
  type: NodePort # type of the service.